name 'dreadnot'
maintainer 'Michael Burns'
maintainer_email 'michael.burns@rackspace.com'
license 'Apache 2.0'
description 'Installs/Configures dreadnot'
long_description 'Installs/Configures dreadnot'
version '0.2.0'

recipe 'dreadnot', 'Installs dreadnot service'
recipe 'stack', 'Config stack'
recipe 'bundle', 'Downloads dreadnot'
recipe 'vhost', 'Setup virtualhost'

depends 'apache2'
depends 'cleanup'
depends 'htpasswd'
depends 'ssl'
depends 'runit'
