name             'dreadnot'
maintainer       'Rackspace'
maintainer_email 'michael.burns@rackspace.com'
license          'Apache 2.0'
description      'Installs/Configures dreadnot'
long_description 'Installs/Configures dreadnot'
version          '0.1.0'
